name: kicad pcb ops CI

on:
  push:
    paths:
    - 'hardware/boards/**.kicad_pcb'
    - 'hardware/boards/**.sch'
    - 'hardware/boards/**.lib'
    - 'hardware/boards/**.dcm'
    - 'hardware/boards/**.pro'
    - 'hardware/boards/**.pretty'
    - 'hardware/boards/fp-lib-table'
    - 'hardware/boards/sym-lib-table'
    - 'hardware/boards/fp-info-cache'
    - '.github/workflows/**'

jobs:
  
  mainboard:
    runs-on: ubuntu-latest
    name: build-mainboard-artifact
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: package schematic and pcbs
      id: hello
      uses: newdigate/kicad-github-action@v0.4.9
      with:
        kicad-project-path: "hardware/boards"
        kicad-schematic-filename: "teensy-eurorack.sch"
        kicad-board-filename: "teensy-eurorack.kicad_pcb"
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: mainboard-artifact
        path: output
    - name: Check the output for success or error
      run: |
        echo "Build result: {{ steps.hello.outputs.message }}"
        if [[ ${{ steps.hello.outputs.success }} != 1 ]]; then
          echo "Build failed: ERC or DRC had errors"
          exit -1
        fi

  breakout:
    runs-on: ubuntu-latest
    name: build-breakout-artifact
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: package schematic and pcbs
      id: hello
      uses: newdigate/kicad-github-action@v0.4.9
      with:
        kicad-project-path: "hardware/boards"
        kicad-schematic-filename: "teensy-eurorack-breakout.sch"
        kicad-board-filename: "teensy-eurorack-breakout.kicad_pcb"
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: breakout-artifact
        path: output
    - name: Check the output for success or error
      run: |
        echo "Build result: {{ steps.hello.outputs.message }}"
        if [[ ${{ steps.hello.outputs.success }} != 1 ]]; then
          echo "Build failed: ERC or DRC had errors"
          exit -1
        fi
